carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
    path('update-cart/', views.update_cart, name='update_cart'),
]

collectaweb/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import ProductListView,EscaparateView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
from users.views import *
from .views import info

urlpatterns = [
    path('', EscaparateView.as_view(), name="index"),
    path('user/login/', views.login_view, name="login"),
    path('user/logout/', views.logout_view, name="logout"),
    path('user/register/', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('categories/', include('categories.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('profile/', perfil ,name = "perfil"),
    path('opiniones/', include('opiniones.urls')),
    path('info/', info, name='info'),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('envio/<slug:slug>/', views.envio, name="envio" ),
    path('seguimiento',views.seguimiento, name='seguimiento'),
    path('estado', views.estado, name='estado'),
    path('pago', views.pago, name='pago' ),
    path('edit',views.SeguimientoEditView , name="edit"),
    path('delete',views.SeguimientoDeleteView , name="delete"),
    path('list',views.SeguimientoListView, name="list"), 
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('',views.ProductListView.as_view() , name="products"),
    path('search',views.ProductSearchListView.as_view() , name="search"),
    path('filter',views.ProductFilterListView.as_view() , name="filter"),
    path('<slug:slug>',views.ProductDetailView.as_view() , name="product"),
    path('<slug:slug>/delete',views.ProductDeleteView , name="product_delete"),
    path('<slug:slug>/edit',views.ProductEditView , name="product_edit"),
    path('create/', views.ProductCreateView, name='product_create'),

]

carts/models.py
import uuid
import decimal
from django.db import models
from users.models import User
from products.models import Product
from django.db.models.signals import pre_save,post_save
from django.db.models.signals import m2m_changed

class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def shipping_cost(self):
        res = 0
        if self.subtotal < 50 and self.subtotal > 0:
            res = 4.99
        return res

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        if self.order:
            self.order.update_total()

    def update_subtotal(self):
        self.subtotal = sum([
            cp.quantity * cp.product.price for cp in self.products_related()
        ])
        self.save() 
    
    def update_total(self):
        self.total = decimal.Decimal(str(float(self.subtotal) + float(self.shipping_cost())))
        self.save() 

    def products_related(self):
    
        return self.cartproducts_set.select_related('product')

    @property
    def order(self):
        return self.order_set.first()



class CartProductsManager(models.Manager):

    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity
        object.update_quantity(quantity)
        return object
class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):

    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()


pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

carts/views.py
from django.shortcuts import render
from products.models import Product
from django.shortcuts import redirect, get_object_or_404
from .models import Cart 
from .utils import get_or_create_cart
from .models import CartProducts
from django.shortcuts import HttpResponse





def cart(request):
    cart = get_or_create_cart(request)

    return render(request, 'carts/cart.html', {

        'cart':cart
    })

def add(request):
    cart = get_or_create_cart(request)
    quantity = int(request.GET.get('quantity'))
    product_id = request.GET.get('product_id')
    product = get_object_or_404(Product, pk=product_id)

    if quantity < 0:
        return
    elif quantity > product.stock:
        return

    new_stock = product.stock-quantity
    product.stock = new_stock
    product.save()
    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart, product=product, quantity=quantity)
    product = Product.objects.get(pk=product_id)
    cart.products.add(product)

    return redirect('/product/'+product.slug)

def remove(request):
    if request.method == 'POST':
        cart = get_or_create_cart(request)
        product_id = request.POST.get('product_id')
        
        try:
            cart_product = CartProducts.objects.get(cart=cart, product__id=product_id)
            quantity = cart_product.quantity
            
  
            cart.products.remove(cart_product.product)
            

            product = cart_product.product
            product.stock += quantity
            product.save()

            return redirect('carts:cart')
        except CartProducts.DoesNotExist:
            return HttpResponse("Producto no encontrado en el carrito")
    else:
        return HttpResponse("Método no permitido")
def update_cart(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        new_quantity = int(request.POST.get('quantity', 1))

        cart = get_or_create_cart(request)
        product = get_object_or_404(Product, pk=product_id)

        try:
            cart_product = CartProducts.objects.get(cart=cart, product=product)
            current_quantity = cart_product.quantity

            
            if new_quantity != current_quantity and 1 <= new_quantity <= product.stock:

                cart_product.update_quantity(new_quantity)

 
                updated_stock = product.stock + current_quantity - new_quantity
                product.stock = updated_stock
                product.save()
        except CartProducts.DoesNotExist:

            pass

   
        return redirect('carts:cart')
    else:

        pass

carts/templates/carts/add.html
{% extends 'base.html' %}
{% load static %}
{% load product_extras %}



{% block content %}

<div class="col-3">
{% if product.image %}
    <img src="{{product.image.url}}" alt="Imagen del producto" with="200" height="200">

{% endif %}
</div>

<div class="col mt-2">
    <div class="h3 font-weight-bold text-success">
    
    {{quantity | quantity_add_format }} al carrito
    </div>
    <div class="h5">
        <a href="{% url 'products:product' product.slug %}">
        {{product.title}}
    </a>
    <div class=" h5 font-weight-bold text-danger">
        {{product.price | price_format }}

    </div>
    <div class="mt-2">
    <a href="{% url 'carts:cart' %}" class="btn btn-warning">Ver Carrito</a>
    </div>
        <div class="mt-2">
     <a href="{% url 'index' %}" class="btn btn-success">Seguir comprando</a>
    </div>

</div>

{% endblock  %}

carts/templates/carts/cart.html
 {% extends 'base.html' %}
{% load product_extras %}

{% block  content %}

{% if cart.products.exists %}
<div class="col-8">
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th  scope="row">🛍️ Producto</th>
                    <th  scope="row">🧮 Cantidad</th>
                    <th  scope="row">💲 Precio</th>
                </tr>
            </thead>
            <tbody>

                {% for cp in cart.products_related %}
                    {% with product=cp.product %}
                <tr>
                    <th>{{ forloop.couter }}</th>
                    <th> 

                        {% if product.image %}
                        <img src="{{ product.image.url}}" alt="Imagen del Producto" width="60" height="60">
                        {% endif%}
                    </th>
                    <th>
                        <a href="{% url 'products:product' product.slug %}">
                            {{ product.title}}
                        </a>
                        <form class="remove-cart-form" method="post" action="{% url 'carts:remove' %}">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{ cp.product.id }}">
                            <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                        </form>
                    </th>
                    <th>
                        <form class="update-cart-form" method="post" action="{% url 'carts:update_cart' %}">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{ cp.product.id }}">
                            <input type="number" name="quantity" value="{{ cp.quantity }}" min="1" max="{{product.stock}}">
                            <button type="submit" class="btn btn-primary btn-sm">Actualizar</button>
                        </form>
                    </th>
                    <th>
                        <span class="font-weight-bold text-danger">{{product.price | price_format}}</span>
                    </th>
                </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
</div>

<div class="col mt-4">
  <div class="card mt-4">
    <div class="card-body">
    <div class="font-weight-bold">
        Subtotal: ({{ cart.products.count}}) <span class="text-danger">{{ cart.subtotal | price_format }}</span><br>
        Gastos de Envio: <span class="text-danger">${{ cart.shipping_cost }}</span><br>
        Total: <span class="text-danger">{{ cart.total | price_format }}</span>
    </div>
    <br>
    <select id="pago" class="form-control" style="min-width:60px;">
        <option value="tarjeta">Pago con tarjeta</option>
        <option value="contrareembolso">Pago contrareembolso</option>

    </select>
    <br>
    <select id="envio" class="form-control" style="min-width:60px;">
        <option value="casa">Envío a domicilio</option>
        <option value="tienda">Recoger en tienda</option>
        <option value="ecológico">Envío ecológico</option>
    </select>
    <div class="mt-2">
        <a id="boton" href="{% url 'orders:pago' %}?cart={{cart.id}}&pago=tarjeta&envio=casa" class="btn btn-success">💳 Proceder al pago</a>
    </div>
    </div>
   </div>
</div>


{% else %}
<div class="col">
    <div class="text-center" style="margin-top:20px">
        <p class="h3">Tu carrito de compras está vacío.</p>
        <a href="{% url 'index' %}" class="btn btn-primary">Seguir comprando</a>
    </div>
</div>
{% endif %}

<script>

    var pagoSelect = document.getElementById('pago');
    var envioSelect = document.getElementById('envio');
    window.onload= function(){
        pagoSelect.value="tarjeta";
        envioSelect.value="casa";
    };

    pagoSelect.addEventListener('change', function() {
        console.log("Evento de cambio de 'pago' disparado");
        var pago = this.value;
        var envio = envioSelect.value;
        console.log("Pago: " + pago);
        console.log("Envio: " + envio);
        var newHref = "{% url 'orders:pago' %}?cart={{cart.id}}&pago=" + this.value + "&envio=" + envio;
        document.getElementById('boton').href = newHref;
    });

    envioSelect.addEventListener('change', function() {
        console.log("Evento de cambio de 'envio' disparado");
        var envio = this.value;
        var pago = pagoSelect.value;
        console.log("Pago: " + pago);
        console.log("Envio: " + envio);
        var newHref = "{% url 'orders:pago' %}?cart={{cart.id}}&pago=" + pago + "&envio=" + envio;
        document.getElementById('boton').href = newHref;
    });
</script>
{% endblock  %}