carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
    path('update-cart/', views.update_cart, name='update_cart'),
]

collectaweb/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import ProductListView,EscaparateView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
from users.views import *
from .views import info

urlpatterns = [
    path('', EscaparateView.as_view(), name="index"),
    path('user/login/', views.login_view, name="login"),
    path('user/logout/', views.logout_view, name="logout"),
    path('user/register/', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('categories/', include('categories.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('profile/', perfil ,name = "perfil"),
    path('opiniones/', include('opiniones.urls')),
    path('info/', info, name='info'),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('',views.ProductListView.as_view() , name="products"),
    path('search',views.ProductSearchListView.as_view() , name="search"),
    path('filter',views.ProductFilterListView.as_view() , name="filter"),
    path('<slug:slug>',views.ProductDetailView.as_view() , name="product"),
    path('<slug:slug>/delete',views.ProductDeleteView , name="product_delete"),
    path('<slug:slug>/edit',views.ProductEditView , name="product_edit"),
    path('create/', views.ProductCreateView, name='product_create'),

]

products/models.py
import uuid
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from producer.models import Producer


class Product(models.Model):
    title = models.CharField(max_length=50)
    description =models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0) 
    slug = models.SlugField(null=False, blank=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='products/', null=True, blank=False)
    stock = models.IntegerField(default=0)
    producer = models.ForeignKey(Producer, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


def set_slug(sender, instance, *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)
        while Product.objects.filter(slug=slug).exists():
            slug = slugify("{}-{}".format(instance.title,str(uuid.uuid4())[:8]))

        instance.slug = slug
pre_save.connect(set_slug, sender=Product)

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from carts.utils import get_or_create_cart
from django.views.generic.list import ListView

from users.models import Admin
from .models import Product, Producer
from django.views.generic.detail import DetailView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


class ProductListView(ListView):
    paginate_by=5
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        producers = Producer.objects.all()
        context = super().get_context_data(**kwargs)
        cart = get_or_create_cart(self.request)
        context['producers'] = producers
        context['cart'] = cart
        context['message'] = 'Listado de Productos'
        context['products'] = context['object_list'] 
        return context
    
class EscaparateView(ListView):
    paginate_by=5
    template_name = 'escaparate.html'
    queryset = Product.objects.exclude(stock=0).order_by('stock')[:3]

    def get_context_data(self, **kwargs):
        producers = Producer.objects.all()
        context = super().get_context_data(**kwargs)
        cart = get_or_create_cart(self.request)
        context['producers'] = producers
        context['cart'] = cart
        context['message'] = 'Listado de Productos'
        context['products'] = context['object_list'] 
        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = 'product.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = get_or_create_cart(self.request)
        context['cart'] = cart
        return context

@login_required
@user_passes_test(Admin.get_user_permissions)
def ProductDeleteView(request, slug):
    producto = Product.objects.filter(slug=slug).first()

    Product.delete(producto)

    return redirect('/')

@login_required
@user_passes_test(Admin.get_user_permissions)
def ProductCreateView(request):
    cart = get_or_create_cart(request)
    if request.method == 'POST':
        
        titulo = request.POST.get('titulo')
        descripcion = request.POST.get('descripcion')
        precio = request.POST.get('precio')
        stock = request.POST.get('stock')
        imagen = request.FILES.get('imagen')  

       
        product = Product(title=titulo, description=descripcion, price=precio, stock=stock, image=imagen)

       
        product.save()


        return redirect('/product/' + product.slug)

    return render(request, 'productCreate.html', {
        'cart': cart
    })

@login_required
@user_passes_test(Admin.get_user_permissions)
def ProductEditView(request, slug):
    product = Product.objects.filter(slug=slug).first()
    cart = get_or_create_cart(request)

    if request.method == 'POST':
     
        titulo = request.POST.get('titulo')
        descripcion = request.POST.get('descripcion')
        precio = request.POST.get('precio')
        stock = request.POST.get('stock')
        imagen = request.FILES.get('imagen')
     

        if titulo != None and titulo != '':
            product.title = titulo
        if descripcion != None and descripcion != '':
            product.description = descripcion
        if precio != None and precio != '':
            product.price = precio
        if stock != None and stock != '':
            product.stock = stock
        if imagen != None and imagen != '':
            product.image = imagen



        product.save()


        return redirect('/product/' + slug)

    return render(request, 'productEdit.html', {
        'product': product,
        'cart': cart
    })

class ProductSearchListView(ListView):
    template_name = 'searchResults.html'
    def get_queryset(self):
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        return Product.objects.filter(filters)

    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = get_or_create_cart(self.request)
        producers = Producer.objects.all()
        context['producers'] = producers
        context['cart'] = cart
        context['query'] = self.query()
        context['count'] = context['object_list'].count()
        return context
    
class ProductFilterListView(ListView):
    template_name = 'filterResults.html'
    def get_queryset(self):
        min, max, producer = self.query()
        products = Product.objects.all()
        if not min=='':
            products = products.filter(price__gte=min)
        if not max=='':
            products = products.filter(price__lte=max)
        if not producer=='':
            products = products.filter(producer=producer)
        return products

    def query(self):
        min = self.request.GET.get('min')
        max = self.request.GET.get('max')
        producer = self.request.GET.get('producer')
        return min, max, producer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cart = get_or_create_cart(self.request)
        context['cart'] = cart
        min, max, producer = self.query()
        if min=='':
            min = 'No se ha establecido'
        context['min'] = min
        if max=='':
            max = 'No se ha establecido'
        context['max'] = max
        if producer=='':
            producer = 'No se ha establecido'
        else: 
            producer = get_object_or_404(Producer,pk=producer)
        context['producer'] = producer
        producers = Producer.objects.all()
        context['producers'] = producers
        context['count'] = context['object_list'].count()
        return context

products/templates/filter.html
<div class="col-lg-2">
    <h3 class="my-4">Filtros</h3>
    <form action="{% url 'products:filter' %}">
        <div class="input-group">
            <div>
                <a>Precio mínimo:</a>
                <input type="number" id="min" min="0" name="min" value="{{query}}" class="form-control" style="min-width:60px;">
                Precio máximo:
                <input type="number" id="max" min="0" name="max" value="{{query}}" class="form-control"style="min-width:60px;">
                Productora:
                <select id="producer" name="producer" class="form-control" style="min-width:60px;">
                    <option value="">---</option>
                    {% for producer in producers %}
                        <option value="{{ producer.id }}">{{ producer.title }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group-append" style="padding-top: 10px;">
                <input type="submit" name="" value="Buscar" class="btn btn-success" style="min-width:60px;">
            </div>
        </div>
    </form>
</div>

<script>
    window.onload = function(){
        min = '{{min}}';
        document.getElementById('min').value = min;
        max = '{{max}}';
        document.getElementById('max').value = max;
        producer = '{{producer.id}}';
        document.getElementById('producer').value = producer;
    }
</script>

products/templates/filterResults.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-10" >
      <br>
      <h3 style="text-align:center">Listado de Productos</h3>
      <ul class="list-group">
        <br>
        {% include 'searchBar.html' %}
        <hr>
        <p><strong>Filtros de busqueda:</strong> Precio mínimo: {{min}}, Precio máximo: {{max}}, Productora: {{producer}} ({{count}})</p>
        {% include 'list.html' %}
      </ul>
    </div>
    {%include 'filter.html' %}
  </div>
{% endblock %}
{% load static %}


<style>
  .row {
    display: flex;
    justify-content: space-between;
  }
 </style>

products/templates/list.html
{% load static %}
<div class="row">
    {% for object in object_list %}
         <ul class="list-group">
               <hr>
               <li class="list-group-item">
                 <div class="d-flex justify-content-between align-items-start" style="width: 925px;">
                      <div class="mr-3">
                           {% if object.image %}
                               <img class="card-img-left" src="{{ object.image.url}}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
                           {% else %}
                               <img class="card-img-left" src="{% static 'images/aimagenot.png' %}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
                           {% endif %} 
                      </div>
                      <div class="mr-3">
                            <h4 class="card-title">{{object.title}}</h4>
                            <p class="card-text"> {{object.description }}</p>
                            <div>
                                <a href="{% url 'products:product' object.slug %}" class="btn btn-outline-success btn-sm">Detalles</a> 
                            </div>
                      </div>
                      <div class="d-flex flex-column">
                           <div>
                              {% if object.stock %}
                              <div>
                                <input type="number" value="1" max="{{ object.stock }}" min="1" class="prueba form-control col-sm-1 d-inline" id="quantity_{{object.id}}" name="quantity" style="min-width:50%;">
                               </div>
                               <div>
                                   <form id="pr_{{object.id}}" method="get" name="{{object.id}}">
                                       {% csrf_token %}
                                       <button type="submit" class="btn btn-outline-warning btn-sm "><span class="fas fa-cart-plus"></span>Añadir al carrito</button>
                                   </form>
                               </div>
                               {% endif %}
                              </div>
                            <div>
                              {% if user.is_staff %}
                                    <user class="is_staff">
                                        <a href="{% url 'products:product' object.slug %}/edit" class="btn btn-outline-warning btn-sm ">Editar</a> 
                                        <a href="{% url 'products:product' object.slug %}/delete" class="btn btn-outline-warning btn-sm ">Eliminar</a> 
                                   </user> 
                                   {% endif %}
                                   </div>
                              <div>
                              {% if object.stock %}
                                   <br><br><a style="color:green">Precio: {{object.price}}€</a>
                              {% else %}
                                   <br><h6 style="color:red">FUERA DE STOCK</h6><strike style="color:red">Precio: {{object.price}}€</strike>
                              {% endif %}

                          </div>
                      </div>
                 </div>
              </li>
         </ul>
    {% endfor %}
    <div class="pagination" style="padding: 40px;" >
          <span class="page-links">
          {% if page_obj.has_previous %}
               <a href="?page={{ page_obj.previous_page_number }}">Página anterior<a>
          {% endif %}
          <span class="page-current">
               Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
          </span>
          {% if page_obj.has_next %}
               <a href="?page={{ page_obj.next_page_number }}">Siguiente página</a>
          {% endif %}
     </span>
     </div>
 </div>
 <script>

     const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
     var forms = Array.from(document.querySelectorAll('form'));
     if (forms[0].name==''){
        forms.shift();


     }
     forms.forEach(form => {
         form.addEventListener('submit', function(e) {
             e.preventDefault();
             const quantity = parseInt(document.getElementById(`quantity_${form.name}`).value);
             const stock = parseInt("{{ object.stock }}");
        if (quantity<1)  {
         alert('La cantidad debe ser mayor que uno');
         return;
        } else if (quantity>stock) {
         alert('La cantidad no debe ser mayor que el stock');
         return;
        }
        const product = form.name
        const url = `{% url 'carts:add' %}?quantity=${quantity}&product_id=${product}`;

        var xhr = new XMLHttpRequest();
     
     
        xhr.open('post', url, true);
     

        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.setRequestHeader('X-CSRFToken', csrftoken);
        
     
        xhr.onload = function() {
            if (xhr.status === 200) {
                alert("Se ha añadido al carrito correctamente");
            } else {
     
                alert('Un error ha sucedido durante la transacción');
            }
        };
     
        xhr.onerror = function() {
            console.error('Un error ha sucedido durante la transacción');
        };
     
        xhr.send();
    });
});
     
     
     </script>

products/templates/product.html
{% extends 'base.html'%}
{% block content %}
  <div class="col-10">
    <h3 style="text-align:center;">Detalles</h1>
    <ul class="list-group">
      <br>
      {% include 'searchBar.html' %}
      <hr>
      {% include 'productDetails.html' %}
    </ul>
  </div>
{% endblock %}
{% load static %}

products/templates/productCreate.html
{% extends 'base.html'%}

{% block content %}
<div class="col">
    <h2>Crear producto</h2>
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            
            <h3>Titulo</h3>
            <div class="form-group">
                <input id="titulo" type="text" name="titulo" class="form-control" placeholder="Titulo" required>
                
            <h3>Descripcion</h3>
            </div>
            <div class="form-group">
                <input id="descripcion" type="text" name="descripcion" class="form-control" placeholder="Descripcion" required>
                
            </div>

            <h3>Precio</h3>
            <div class="form-group">
                <input id="precio" type="number" name="precio"  class="form-control" placeholder="Price" required>
                
            <h3>Stock</h3>
            </div>
            <div class="form-group">
                <input id="stock" type="number" name="stock" class="form-control" placeholder="Stock" required>
                
            <h3>Imagen</h3>
            </div>
            <div class="form-group">
                <input id="imagen" type="file" name="imagen" class="form-control" placeholder="Imagen" required>
                
            </div>

            <button type="submit" class="btn btn-primary">Crear</button>
         
        </form>
</div>
{% endblock %}

products/templates/productDetails.html
{% load static %}
{% block content %}
<div class="d-flex justify-content-between align-items-start" style="width: 925px;">
    <div class="mr-3">
         {% if product.image %}
             <img class="card-img-left" src="{{ product.image.url}}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
         {% else %}
             <img class="card-img-left" src="{% static 'images/aimagenot.png' %}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
         {% endif %} 
    </div>
    <div class="mr-3">
          <h2 class="card-title"><u>{{product.title}}</u></h2>
          <a style="color:green">Precio: {{product.price}}€</a>
          <div>
            {% if product.stock %}
                <a>Disponibilidad: </a><a style="color:green">EN STOCK </a><a> {{product.stock}} unidades restantes</a>
            {% else %}
                <a>Disponibilidad: </a><a style="color:red">FUERA DE STOCK</a>
            {% endif %}
            </div>
          <p class="card-text"> {{product.description }}</p>
    </div>
    <div class="d-flex flex-column">
        {% if product.stock %}
        <div>
            <input type="number" value="1" max="{{ product.stock }}" min="1" class="prueba form-control col-sm-1 d-inline" id="quantity" name="quantity" style="min-width:50%;">
        </div>
        <div>
            <form id="form" action="#" method="get">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-warning btn-sm "><span class="fas fa-cart-plus"></span>Añadir al carrito</button>
            </form>
        </div>
        {% endif %}
        <div>
            {% if user.is_staff%}
            <user class="is_staff">
                <a href="{% url 'products:product' object.slug %}/edit" class="btn btn-outline-warning btn-sm ">Editar</a> 
                <a href="{% url 'products:product_delete' object.slug %}?quantity=1" class="btn btn-outline-warning btn-sm ">Eliminar</a> 
           </user> 
           {% endif %}
           </div>
    </div>
</div>
<script>
const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
document.getElementById('form').addEventListener('submit', function(e) {
   e.preventDefault();
   const quantity = parseInt(document.getElementById('quantity').value);
   const stock = parseInt("{{ product.stock }}");
   if (quantity<1)  {
    alert('La cantidad no puede ser menor que 1');
    return;
   } else if (quantity>stock) {
    alert('la cantidad no puede ser maoyr que el stock');
    return;
   }
   const product = "{{ product.id }}";
   const url = `{% url 'carts:add' %}?quantity=${quantity}&product_id=${product}`;

   var xhr = new XMLHttpRequest();


   xhr.open('post', url, true);


   xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
   xhr.setRequestHeader('X-CSRFToken', csrftoken);

   xhr.onload = function() {
       if (xhr.status === 200) {
           alert("Se ha añadido al carrito correctamente");
       } else {

           alert('An error occurred during the transaction');
       }
   };

   xhr.onerror = function() {
       console.error('An error occurred during the transaction');
   };

   xhr.send();
});

</script>
{% endblock %}

products/templates/productEdit.html
{% extends 'base.html'%}

{% block content %}
<div class="col">
    <h2>Editar producto: {{product.title}}</h2>
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            
            <h3>Titulo</h3>
            <div class="form-group">
                <input id="titulo" type="text" name="titulo" class="form-control" placeholder="Titulo">
                
            <h3>Descripcion</h3>
            </div>
            <div class="form-group">
                <input id="descripcion" type="text" name="descripcion" class="form-control" placeholder="Descripcion">
                
            </div>

            <h3>Precio</h3>
            <div class="form-group">
                <input id="precio" type="number" name="precio"  class="form-control" placeholder="Price">
                
            <h3>Stock</h3>
            </div>
            <div class="form-group">
                <input id="stock" type="number" name="stock" class="form-control" placeholder="Stock">
                
            <h3>Imagen</h3>
            </div>
            <div class="form-group">
                <input id="imagen" type="file" name="imagen" class="form-control" placeholder="Imagen">
                
            </div>

            <button type="submit" class="btn btn-primary">Registar</button>
         
        </form>
</div>

<script>

    window.onload = function(){

        var titulo = "{{ product.title }}"; 
        document.getElementById('titulo').value = titulo;

        var descripcion = "{{ product.description }}";
        document.getElementById('descripcion').value = descripcion;

        var precio = "{{ product.price }}";
        document.getElementById('precio').value = precio;

        var stock = "{{ product.stock }}";
        document.getElementById('stock').value = stock;

        var imagen = "{{ product.image }}";
        document.getElementById('imagen').value = imagen;
    };
</script>
{% endblock %}

products/templates/searchBar.html
<form action="{% url 'products:search' %}">
    <div class="input-group">
        <input type="text" name="q" value="{{query}}" class="form-control" placeholder="Buscar producto">
        <div class="input-group-append">
            <input type="submit" name="" value="Buscar" class="btn btn-success">
        </div>
    </div>
</form>

products/templates/searchResults.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-10" >
      <br>
      <h3 style="text-align:center">Listado de Productos</h3>
      <ul class="list-group">
        <br>
        {% include 'searchBar.html' %}
        <hr>
        <p>Resultados de la busqueda: {{query}} ({{count}})</p>
        {% include 'list.html' %}
      </ul>
    </div>
    {%include 'filter.html' %}
  </div>
{% endblock %}
{% load static %}


<style>
  .row {
    display: flex;
    justify-content: space-between;
  }
 </style>