carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
    path('update-cart/', views.update_cart, name='update_cart'),
]

collectaweb/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import ProductListView,EscaparateView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
from users.views import *
from .views import info

urlpatterns = [
    path('', EscaparateView.as_view(), name="index"),
    path('user/login/', views.login_view, name="login"),
    path('user/logout/', views.logout_view, name="logout"),
    path('user/register/', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('categories/', include('categories.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('profile/', perfil ,name = "perfil"),
    path('opiniones/', include('opiniones.urls')),
    path('info/', info, name='info'),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('envio/<slug:slug>/', views.envio, name="envio" ),
    path('seguimiento',views.seguimiento, name='seguimiento'),
    path('estado', views.estado, name='estado'),
    path('pago', views.pago, name='pago' ),
    path('edit',views.SeguimientoEditView , name="edit"),
    path('delete',views.SeguimientoDeleteView , name="delete"),
    path('list',views.SeguimientoListView, name="list"), 
]

orders/models.py
import uuid
from enum import Enum
from django.db import models
from users.models import User
from carts.models import Cart
from django.db.models.signals import pre_save




class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    correo = models.EmailField(blank=True)
    shipping_total = models.DecimalField(default=5, max_digits=8, decimal_places=2)
    subtotal = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    enviado= models.DateField(null=True, blank=True)
    entregado=models.DateField(null=True,blank=True)
    nombre = models.CharField(max_length=40, null=True, blank=False, unique=False)
    apellidos = models.CharField(max_length=40, null=True, blank=False, unique=False)
    calle = models.CharField(max_length=40, null=True, blank=False, unique=False)
    numero = models.IntegerField(null=True, blank=False, unique=False)
    codigopostal = models.IntegerField(null=True, blank=False, unique=False)
    ciudad = models.CharField(max_length=40, null=True, blank=False, unique=False)
    tarjeta = models.CharField(max_length=16, null=True, blank=True)
    cvv = models.CharField(max_length=3, null=True, blank=True)
    fechacad = models.CharField(max_length=5, null=True, blank=True)



    def __str__(self):
        return self.order_id

    def get_total(self):
        return self.cart.total

    def update_total(self):
        self.total = self.get_total()
        self.save()

    def estado(self):

        res= "En proceso"

        if self.enviado != None:
            if self.entregado !=None:
                res= "Entregado"
            else:
                res= "Enviado"
        return res
        

def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())


def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

orders/views.py
from django.shortcuts import get_object_or_404, redirect, render
from carts.utils import get_or_create_cart
from .models import Order, Cart
from django.contrib.auth.decorators import login_required
from .utils import breadcrumb
from django.views.generic.list import ListView
from django.utils import timezone
from django.conf import settings
from django.core.mail import send_mail


@login_required(login_url='login')
def order(request):
    cart = get_or_create_cart(request)
    order = cart.order
    if order is None and request.user.is_authenticated:
        order = Order.objects.create(cart=cart, user=request.user)
    if order:
        request.session['order_id'] = order.order_id
    return render(request, 'orders/order.html', {
        'cart': cart,
        'breadcrumb': breadcrumb()
    })

def envio(request, slug):
    order = get_object_or_404(Order, order_id=slug)
    

    cart_products = order.cart.products_related()


    email_content = f'Gracias por tu compra en nuestro sitio.\n\nDetalles de la compra:\n\n'
    for cart_product in cart_products:
        email_content += f"Producto: {cart_product.product.title}\n"
        email_content += f"Cantidad: {cart_product.quantity}\n"
        
    email_content += f'Importe: {order.total}\nDirección de entrega: {order.calle} {order.numero}, {order.ciudad}, {order.codigopostal}'

   
    send_mail(
        'Confirmación de compra',
        email_content,
        'collectaweb.pgpi@gmail.com', 
        [order.correo],  
        fail_silently=False,
    )
    context = {'order': order}
    return render(request, 'orders/id_envio.html', context)

def seguimiento(request):
    user = request.user if request.user.is_authenticated else None
    cart = get_or_create_cart(request)
    if user != None:
        orders = Order.objects.filter(user=request.user).order_by('-id')
    else:
        orders = []
    return render(request, 'orders/seguimiento.html', {
        'object_list': orders, 
        'admin': False, 
        'cart': cart
        })

def estado(request):
    order_id = request.GET.get('slug')
    cart = get_or_create_cart(request)
    order = get_object_or_404(Order, order_id=order_id)
    context = {'order': order, 'cart': cart}
    return render(request, 'orders/estadopedido.html', context)

def pago(request):
    id= request.GET.get("cart")
    cart = get_object_or_404(Cart, pk=id)
    pago=request.GET.get("pago")
    if pago=="tarjeta":
        pago=True
    else:
        pago=False
    envio=request.GET.get("envio")
    if not envio=="tienda":
        envio=True
    else:
        envio=False
    context = {'pago':pago,
                'envio':envio,
                'cart':cart}
    if request.method == 'POST':
        cart.user = None
        cart.save()
        request.session['cart_id'] = None
        order=Order.objects.create(
            cart=cart,
            user=request.user if request.user.is_authenticated else None)
        nombre = request.POST.get('firstName')
        apellidos = request.POST.get('lastName')
        correo = request.POST.get('email')
        calle = request.POST.get('street')
        numero = request.POST.get('number')
        codigopostal = request.POST.get('postalCode')
        ciudad = request.POST.get('city')
        tarjeta = request.POST.get('cardNumber')
        cvv = request.POST.get('cvv') 
        fechacad = request.POST.get('expiryDate')
        guardar = request.POST.get('save')

        order.subtotal = cart.subtotal 
        order.update_total()
        order.nombre=nombre
        order.apellidos=apellidos
        order.correo=correo
        order.calle = calle
        order.numero = numero
        order.codigopostal=codigopostal
        order.ciudad=ciudad
        order.tarjeta=tarjeta
        order.cvv=cvv
        order.fechacad=fechacad

        user = request.user if request.user.is_authenticated else None
        if guardar and user !=None:
            user.first_name=nombre
            user.last_name=apellidos
            user.email=correo
            user.calle = calle
            user.numero = numero
            user.codigopostal=codigopostal
            user.ciudad=ciudad
            user.tarjeta=tarjeta
            user.cvv=cvv
            user.fechacad=fechacad
            user.save()


        order.save()


        return redirect('/order/envio/' + order.order_id)
    return render(request, 'orders/pasarelapago.html', context)


def SeguimientoDeleteView(request):
    order_id = request.GET.get('slug')
    order = Order.objects.filter(order_id=order_id).first()

    Order.delete(order)

    return redirect('/')

def SeguimientoListView(request):
    orders = Order.objects.all().order_by('-id')
    cart = get_or_create_cart(request)
    context = {
        'orders': orders, 'admin': True, 'cart': cart
    }
    return render(request, 'orders/listOrders.html', context)


def SeguimientoEditView(request):
    order_id = request.GET.get('slug')
    order = Order.objects.filter(order_id=order_id).first()
    cart = get_or_create_cart(request)
    context = {'object_list': order, 'cart': cart}
    
    if request.method == 'POST' and not order.enviado:
        
        order.enviado  = timezone.now()
        


        order.save()

        return redirect('/order/edit?slug=' + order_id)
    
    if request.method == 'POST' and order.enviado:
        
        order.entregado = timezone.now()
        



        order.save()


        return redirect('/order/edit?slug=' + order_id)
    
    return render(request, 'orders/orderEdit.html', {
        'order': order
    })

orders/templates/orders/estadopedido.html
{% extends 'base.html'%}

{% block breadcrumb %}
 {% include 'orders/snippets/breadcrumb.html'%}
{% endblock %}

{% block  content %}
<div style="width: 50%; margin: auto;">
    <h1 style="text-align: center;">Su pedido se encuentra:</h1>
    <h2 style="text-align: center; margin-top: 20px; color: 
        {% if order.estado == 'En proceso' %}#0000FF
        {% elif order.estado == 'Entregado' %}#008000
        {% elif order.estado == 'Enviado' %}#90EE90
        {% elif order.estado == 'No se ha realizado el pago' %}#FF0000
        {% endif %};">
        {{order.estado}}
    </h2>
</div>
{% if user.is_staff %}
    <div class="col-10 d-flex justify-content-center my-4">
      <a href="{% url 'orders:edit' %}?slug={{order.order_id}}" class="btn btn-outline-warning btn-sm ">Editar pedido</a> 
      <a href="{% url 'orders:delete' %}?slug={{order.order_id}}" class="btn btn-outline-warning btn-sm ">Eliminar pedido</a> 
    </div>
  {% endif %}
{% endblock  %}

orders/templates/orders/id_envio.html
{% extends 'base.html'%}

{% block breadcrumb %}
 {% include 'orders/snippets/breadcrumb.html'%}
{% endblock %}

{% block  content %}
<style>
  .content-center {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }
  .order-code {
    padding: 10px;
    background-color: #f8f9fa;
    border: 1px solid #dee2e6;
    border-radius: 5px;
    font-size: 1.2em;
    color: #495057;
    text-align: center;
  }
  .copy-button {
    margin-top: 10px;
    padding: 5px 10px;
    cursor: pointer;
  }
</style>

<div class="content-center">
  <h2>Guarda este código de forma segura, podrás ver la situación de tu pedido:</h2>
  <div class="order-code">
    <h5>{{order}}</h5>
  </div>
  <button class="copy-button" onclick="navigator.clipboard.writeText('{{order}}')">Copiar código</button>
</div>
<div class="col-10 d-flex justify-content-center my-4">
    <p><a href="#">Políticas de la empresa</a></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <p><a href="#">Términos y condiciones</a></p>
</div>
{% endblock  %}

orders/templates/orders/listOrders.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<style>

</style>
  <div class="col-10">
    <h3 style="text-align: center;">Lista de Pedidos</h3>
    <ul class="list-group">
      <br>
      {% include 'searchBar.html' %}
      <hr>
      {% include 'orders/orders.html' %}
    </ul>
  </div>
{% endblock %}
{% load static %}

orders/templates/orders/order.html
{% extends 'base.html'%}

{% block breadcrumb %}
 {% include 'orders/snippets/breadcrumb.html'%}
{% endblock %}


{% block  content %}
<div class="col-8">
    <div class="h3">
            Revisa tu pedido
    </div>

    <div class="card">
        <div class="card-body">
            {% for product in cart.products.all %}
                {% include 'orders/snippets/product.html' %}
            {% endfor %}
        </div>
    </div>
</div>

<div>
    {% include 'orders/snippets/resume.html' %}

</div>
{% endblock  %}

orders/templates/orders/orderEdit.html
{% extends 'base.html'%}

{% block content %}
<div class="col">
    <h2 >Editar seguimiento:</h2>
<h3>
    Estado actual: <a style="margin-top: 20px; color: 
    {% if order.estado == 'En proceso' %}#0000FF
    {% elif order.estado == 'Entregado' %}#008000
    {% elif order.estado == 'Enviado' %}#90EE90
    {% elif order.estado == 'No se ha realizado el pago' %}#FF0000
    {% endif %};"> 
    {{order.estado}}</a>
</h3>

    {% if not order.enviado %}
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            
            <button type="submit" class="btn btn-primary" >Marcar como enviado</button>
         
        </form>
    {% endif %}

    {% if order.enviado and not order.entregado %}
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}

            <button type="submit" class="btn btn-primary" >Marcar como entregado</button>
         
        </form>
    {% endif %}

</div>

{% endblock %}

orders/templates/orders/orders.html
{% load static %}
<div class="row">
    {% for object in orders %}
         <ul class="list-group">
               <hr>
               <li class="list-group-item">
                 <div class="d-flex justify-content-between align-items-start" style="width: 925px;">
                      <div class="mr-3">
                        <h4 class="card-title" ><span style="color: blue;">{{object.order_id}}</span> esta: <span style="color: 
                          {% if object.estado == 'En proceso' %}#0000FF
                          {% elif object.estado == 'Entregado' %}#008000
                          {% elif object.estado == 'Enviado' %}#90EE90
                          {% elif object.estado == 'No se ha realizado el pago' %}#FF0000
                          {% endif %};">
                          {{object.estado}}</span></h4>
                          <h3 class="card-title">Descripción del pedido:</h3>
                          <p class="card-text"> Nombre: {{object.nombre }}</p>
                          <p class="card-text"> Apellidos: {{object.apellidos }}</p>
                          <p class="card-text"> Calle: {{object.calle }}</p>
                          <p class="card-text"> Numero: {{object.numero }}</p>
                          <p class="card-text"> Codigo Postal: {{object.codigopostal }}</p>
                          <p class="card-text"> Ciudad: {{object.ciudad }}</p>
                          {%if admin%}
                          <a href="{% url 'orders:edit' %}?slug={{object.order_id}}" class="btn btn-outline-warning btn-sm ">Editar pedido</a> 
                          <a href="{% url 'orders:delete' %}?slug={{object.order_id}}" class="btn btn-outline-warning btn-sm ">Eliminar pedido</a> 
                          {%endif%}
                         </div>
                 </div>
              </li>
         </ul>
    {% endfor %}
 </div>

orders/templates/orders/pagocontrareembolso.html
{% extends 'base.html'%}
{% block content %}
 <div class="col-10 d-flex justify-content-center my-4">
 <form method="post"  id="paymentForm">{% csrf_token %}
   <h2>Datos del cliente</h2>

 <div class="form-group">
 <label for="firstName">Nombre*</label>
 <input type="text" id="firstName" name="firstName" class="form-control" placeholder="Ingrese su nombre" required>
 </div>
 <div class="form-group">
 <label for="lastName">Apellido*</label>
 <input type="text" id="lastName" name="lastName" class="form-control" placeholder="Ingrese su apellido" required>
 </div>
 <h2>Detalles del envío</h2>
 <div class="form-group">
 <label for="street">Calle*</label>
 <input type="text" id="street" name="street" class="form-control" placeholder="Ingrese la calle" required>
 </div>
 <div class="form-group">
 <label for="number">Número*</label>
 <input type="number" id="number" name="number" class="form-control" placeholder="Ingrese el número" required>
 </div>
 <div class="form-group">
 <label for="postalCode">Código Postal*</label>
 <input type="text" id="postalCode" name="postalCode" class="form-control" placeholder="Ingrese el código postal" required>
 </div>
 <div class="form-group">
 <label for="city">Ciudad*</label>
 <input type="text" id="city" name="city" class="form-control" placeholder="Ingrese la ciudad" required>
 </div>
 <div class="input-group-append">
    <button type="submit" id="confirmPayment" class="btn btn-warning" href="/envio/{{order.order_id}}">Confirmar envío</button>
 </div>
 <div><h6>(*) Campo obligatorio</h6></div>
 </form>
 </div>
 <div class="col-10 d-flex justify-content-center my-4">
 <p><a href="#">Políticas de la empresa</a></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 <p><a href="#">Términos y condiciones</a></p>
 </div>
{% endblock %}
{% load static %}

orders/templates/orders/pasarelapago.html
{% extends 'base.html'%}
{% block content %}
<div class="col-10 d-flex justify-content-center my-4">
  <form method="post" id="paymentForm">{% csrf_token %}
    <h2>Datos del cliente</h2>

    <div class="form-group">
      <label for="firstName">Nombre*</label>
      <input type="text" id="firstName" name="firstName" class="form-control" placeholder="Ingrese su nombre" required>
    </div>
    <div class="form-group">
      <label for="lastName">Apellido*</label>
      <input type="text" id="lastName" name="lastName" class="form-control" placeholder="Ingrese su apellido" required>
    </div>
    <div class="form-group">
      <label for="email">Correo</label>
      <input type="text" id="email" name="email" class="form-control" placeholder="Ingrese su correo" required>
    </div>
    {%if envio%}
    <h2>Detalles del envío</h2>
    <div class="form-group">
      <label for="street">Calle*</label>
      <input type="text" id="street" name="street" class="form-control" placeholder="Ingrese la calle" required>
    </div>
    <div class="form-group">
      <label for="number">Número*</label>
      <input type="number" id="number" name="number" class="form-control" placeholder="Ingrese el número" required>
    </div>
    <div class="form-group">
      <label for="postalCode">Código Postal*</label>
      <input type="text" id="postalCode" name="postalCode" class="form-control" placeholder="Ingrese el código postal"
        required>
    </div>
    <div class="form-group">
      <label for="city">Ciudad*</label>
      <input type="text" id="city" name="city" class="form-control" placeholder="Ingrese la ciudad" required>
    </div>
    {%endif%}
    {%if pago%}
    <h2>Detalles de la tarjeta de pago</h2>
    <div class="form-group">
      <label for="cardNumber">Número de tarjeta*</label>
      <input type="text" id="cardNumber" name="cardNumber" class="form-control"
        placeholder="Ingrese el número de tarjeta" pattern="\d{16}" required>
    </div>
    <div class="form-group">
      <label for="cvv">CVV*</label>
      <input type="text" id="cvv" name="cvv" class="form-control" placeholder="Ingrese el CVV" pattern="\d{3}" required>
    </div>
    <div class="form-group">
      <label for="expiryDate">Fecha de caducidad*</label>
      <input type="text" id="expiryDate" name="expiryDate" class="form-control" placeholder="MM/AA"
        pattern="(0[1-9]|1[0-2])\/?([0-9]{4}|[0-9]{2})" required>
    </div>
    {%endif%}
    {%if user.is_authenticated%}
    <div class="form-group">
      <a>Guardar los datos:
      <input type="checkbox" id="save" name="save" class="form-control"></a>
    </div>
    {%endif%}
    <div class="input-group-append">
      <button type="submit" id="confirmPayment" class="btn btn-warning" href="/envio/{{order.order_id}}">Confirmar
        pago</button>
    </div>
    <div>
      <h6>(*) Campo obligatorio</h6>
    </div>
  </form>
</div>

<div class="col-10 d-flex justify-content-center my-4">
  <p><a href="#">Políticas de la empresa</a></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <p><a href="#">Términos y condiciones</a></p>
</div>

<script>

  window.onload = function(){

      var nombre = "{{ user.first_name }}"; 
      if(nombre!="None"){
      document.getElementById('firstName').value = nombre;
      }

      var apellidos = "{{ user.last_name }}";
      if(apellidos!="None"){
      document.getElementById('lastName').value = apellidos;
      }

      var correo = "{{ user.email }}";
      if(correo!="None"){
      document.getElementById('email').value = correo;
      }
      var calle = "{{ user.calle }}";
      if(calle!="None"){
      document.getElementById('street').value = calle;
      }

      var numero = "{{ user.numero }}";
      if(numero!="None"){
      document.getElementById('number').value = numero;
      }

      var codigopostal = "{{ user.codigopostal }}";
      if(codigopostal!="None"){
      document.getElementById('postalCode').value = codigopostal;
      }

      var ciudad = "{{ user.ciudad }}";
      if(ciudad!="None"){
      document.getElementById('city').value = ciudad;
      }

      var tarjeta = "{{ user.tarjeta }}";
      if(tarjeta!="None"){
      document.getElementById('cardNumber').value = tarjeta;
      }

      var cvv = "{{ user.cvv }}";
      if(cvv!="None"){
      document.getElementById('cvv').value = cvv;
      }
      var fechacad = "{{ user.fechacad }}";
      if(fechacad!="None")
      document.getElementById('expiryDate').value = fechacad;
  };
</script>
{% endblock %}
{% load static %}

orders/templates/orders/seguimiento.html
{% extends 'base.html'%}
{% block content %}
 <div class="container my-4">
   <div class="row justify-content-center">
     <div class="col-md-8">
       <form action="{% url 'orders:estado' %}">
         <div class="form-group">
           <h1>Seguimiento de pedido</h1>
           <input type="text" id="orderNumber" name="slug" value="{{query}}" class="form-control" placeholder="Ingrese el número de pedido" pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" required>
         </div>
         <div class="form-group">
           <input type="submit" value="Localizar envío" class="btn btn-primary btn-block">
         </div>
       </form>
     </div>
     {%include 'orders/orders.html' %}
   </div>
 </div>
 <div class="col-10 d-flex justify-content-center my-4">
  <p><a href="#">Políticas de la empresa</a></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <p><a href="#">Términos y condiciones</a></p>
</div>
{% endblock %}
{% load static %}