carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
    path('update-cart/', views.update_cart, name='update_cart'),
]

categories/urls.py
from django.urls import path
from . import views

app_name = 'categories'

urlpatterns = [
    path('<slug:slug>',views.category , name="category"),
    path('', views.categories, name='categories'),
    path('create/', views.CategoryCreateView, name='categories_create'),
    path('<slug:slug>/delete',views.CategoryDeleteView , name="categories_delete"),
    path('<slug:slug>/edit',views.CategoryEditView , name="categories_edit"),
]

collectaweb/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import ProductListView,EscaparateView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
from users.views import *
from .views import info

urlpatterns = [
    path('', EscaparateView.as_view(), name="index"),
    path('user/login/', views.login_view, name="login"),
    path('user/logout/', views.logout_view, name="logout"),
    path('user/register/', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('categories/', include('categories.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('profile/', perfil ,name = "perfil"),
    path('opiniones/', include('opiniones.urls')),
    path('info/', info, name='info'),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('',views.ProductListView.as_view() , name="products"),
    path('search',views.ProductSearchListView.as_view() , name="search"),
    path('filter',views.ProductFilterListView.as_view() , name="filter"),
    path('<slug:slug>',views.ProductDetailView.as_view() , name="product"),
    path('<slug:slug>/delete',views.ProductDeleteView , name="product_delete"),
    path('<slug:slug>/edit',views.ProductEditView , name="product_edit"),
    path('create/', views.ProductCreateView, name='product_create'),

]

categories/models.py
import uuid
from django.db import models
from products.models import Product
from django.utils.text import slugify
from django.db.models.signals import pre_save

class Category(models.Model):
    title = models.CharField(max_length=50)
    description =models.TextField()
    products =models.ManyToManyField(Product, blank=True)
    slug = models.SlugField(null=False, blank=False, unique=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='categories/', null=True, blank=False)
    def __str__(self):
        return self.title

def set_slug(sender, instance, *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)
        while Category.objects.filter(slug=slug).exists():
            slug = slugify("{}-{}".format(instance.title,str(uuid.uuid4())[:8]))
        instance.slug = slug

pre_save.connect(set_slug, sender=Category)

categories/views.py
from django.shortcuts import render,redirect
from carts.utils import get_or_create_cart
from .models import Category
from django.views.generic.list import ListView
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required
from users.models import Admin

def categories(request):
    categories = Category.objects.all()
    cart = get_or_create_cart(request)
    return render(request, 'categories.html', {
        'object_list':categories,
        'cart': cart
    })

def category(request, slug):
    category = Category.objects.filter(slug=slug).first()
    products = category.products.all()
    cart = get_or_create_cart(request)

    return render(request, 'category.html', {
        'object_list':products,
        'category': category.title,
        'cart': cart
    })

@login_required
@user_passes_test(Admin.get_user_permissions)
def CategoryDeleteView(request, slug):
    category = Category.objects.filter(slug=slug).first()

    Category.delete(category)

    return redirect('/categories' )

@login_required
@user_passes_test(Admin.get_user_permissions)
def CategoryCreateView(request):
    cart = get_or_create_cart(request)

    if request.method == 'POST':

        titulo = request.POST.get('titulo')
        descripcion = request.POST.get('descripcion')
        imagen = request.FILES.get('imagen') 


        categoria = Category(title=titulo, description=descripcion, image=imagen)

        categoria.save()


        return redirect('/categories' )

    return render(request, 'categoryCreate.html', {
        'cart': cart
    })

@login_required
@user_passes_test(Admin.get_user_permissions)
def CategoryEditView(request, slug):
    category = Category.objects.filter(slug=slug).first()
    cart = get_or_create_cart(request)

    if request.method == 'POST':

        titulo = request.POST.get('titulo')
        descripcion = request.POST.get('descripcion')
        imagen = request.FILES.get('imagen')
        category.title = titulo
        category.description = descripcion
        category.image = imagen
        category.save()

        return redirect('/categories' )

    return render(request, 'categoryEdit.html', {
        'category': category,
        'cart': cart
    })

categories/templates/categories.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<style>

</style>
  <div class="col-10">
    <h3 style="text-align: center;">Lista de Categorias</h3>
    <ul class="list-group">
      <br>
      {% include 'searchBar.html' %}
      <hr>
      {% include 'listCategories.html' %}
    </ul>
  </div>
{% endblock %}
{% load static %}

categories/templates/category.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
  <div class="col-10">
    <h3 style="text-align: center;">Lista de productos de {{ category }}</h3>
    <ul class="list-group">
      <br>
      {% include 'searchBar.html' %}
      <hr>
      {% include 'listProducts.html' %}
    </ul>
  </div>
{% endblock %}
{% load static %}

categories/templates/categoryCreate.html
{% extends 'base.html'%}

{% block content %}
<div class="col">
    <h2>Crear categoria</h2>
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            
            <h3>Titulo</h3>
            <div class="form-group">
                <input id="titulo" type="text" name="titulo" class="form-control" placeholder="Titulo" required>
                
            <h3>Descripcion</h3>
            </div>
            <div class="form-group">
                <input id="descripcion" type="text" name="descripcion" class="form-control" placeholder="Descripcion" required>
                
            </div>

            
            <h3>Imagen</h3>
            <div>
            <div class="form-group">
                <input id="imagen" type="file" name="imagen" class="form-control" placeholder="Imagen" required>
                
            </div>

            <button type="submit" class="btn btn-primary">Crear</button>
         
        </form>
</div>
{% endblock %}

categories/templates/categoryEdit.html
{% extends 'base.html'%}

{% block content %}
<div class="col">
    <h2>Editar categoria: {{product.title}}</h2>
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            
            <h3>Titulo</h3>
            <div class="form-group">
                <input id="titulo" type="text" name="titulo" class="form-control" placeholder="Titulo">
                
            <h3>Descripcion</h3>
            </div>
            <div class="form-group">
                <input id="descripcion" type="text" name="descripcion" class="form-control" placeholder="Descripcion">
                
            </div>
            
            <h3>Imagen</h3>
            <div>
            <div class="form-group">
                <input id="imagen" type="file" name="imagen" class="form-control" placeholder="Imagen">
                
            </div>

            <button type="submit" class="btn btn-primary">Registar</button>
         
        </form>
</div>

<script>

    window.onload = function(){

        var titulo = "{{ product.title }}"; 
        document.getElementById('titulo').value = titulo;

        var descripcion = "{{ product.description }}";
        document.getElementById('descripcion').value = descripcion;

        var imagen = "{{ product.image }}";
        document.getElementById('imagen').value = imagen;
    };
</script>
{% endblock %}

categories/templates/listCategories.html
{% load static %}
<div class="row">
    {% for object in object_list %}
         <ul class="list-group">
               <hr>
               <li class="list-group-item">
                 <div class="d-flex justify-content-between align-items-start" style="width: 925px;">
                      <div class="mr-3">
                           {% if object.image %}
                               <img class="card-img-left" src="{{ object.image.url}}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
                           {% else %}
                               <img class="card-img-left" src="{% static 'images/aimagenot.png' %}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
                           {% endif %} 
                      </div>
                      <div class="mr-3">
                            <h4 class="card-title">{{object.title}}</h4>
                            <p class="card-text"> {{object.description }}</p>
                      </div>
                      <div>
                         <a href="{% url 'categories:category' object.slug %}" class="btn btn-outline-success btn-sm">Ver productos de esta categoria</a> 
                      </div>
                      {% if user.is_staff %}
                         <user class="is_staff">
                              <a href="{% url 'categories:category' object.slug %}/edit" class="btn btn-outline-warning btn-sm ">Editar</a> 
                              <a href="{% url 'categories:category' object.slug %}/delete" class="btn btn-outline-warning btn-sm ">Eliminar</a> 
                         </user> 
                       {% endif %}
                 </div>
              </li>
         </ul>
    {% endfor %}
 </div>

categories/templates/listProducts.html
{% load static %}
<div class="row">
    {% for object in object_list %}
         <ul class="list-group">
               <hr>
               <li class="list-group-item">
                 <div class="d-flex justify-content-between align-items-start" style="width: 925px;">
                      <div class="mr-3">
                           {% if object.image %}
                               <img class="card-img-left" src="{{ object.image.url}}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
                           {% else %}
                               <img class="card-img-left" src="{% static 'images/aimagenot.png' %}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
                           {% endif %} 
                      </div>
                      <div class="mr-3">
                            <h4 class="card-title">{{object.title}}</h4>
                            <p class="card-text"> {{object.description }}</p>
                            <div>
                                <a href="{% url 'products:product' object.slug %}" class="btn btn-outline-success btn-sm">Detalles</a> 
                            </div>
                      </div>
                      <div class="d-flex flex-column">
                           <div>
                               <a href="{% url 'products:product' object.slug %}" class="btn btn-outline-warning btn-sm "><span class="fas fa-cart-plus"></span>Añadir al carrito</a> 
                           </div>
                           <div>
                              {% if object.stock %}
                                   <br><br><a style="color:green">Precio: {{object.price}}€</a>
                              {% else %}
                                   <br><h6 style="color:red">FUERA DE STOCK</h6><strike style="color:red">Precio: {{object.price}}€</strike>
                              {% endif %}

                          </div>
                      </div>
                 </div>
              </li>
         </ul>
    {% endfor %}
 </div>

categories/templates/searchResults.html
{% extends 'base.html' %}
{% block content %}
    <div class="col">
        <br>
        {% include 'searchBar.html' with query=query %}
        <hr>
        <p>Search results: {{query}} ({{count}})</p>
        {% include 'products/snippets/list.html' %}
    </div>
{% endblock %}